grpc_url = "http://rpc.neutron.quokkastake.io"
grpc_port = "9090"
chain_id = "neutron-1"
authorizations = "neutron19exqhs74rn227jhu2puh9wkvhmse0ugxfnekgzkhfu6c3lxslcasueyxmv"
processor = "neutron1cs24zcgjfv0mv2j53r9jtsmzl0c0fwne9w29jcrs43qusr03pnhqfe8mk6"
cw20 = "neutron1acr52sxxg7tuvx70vm7ucsme93ywlwveprtm6uknhghu9jcpkfhqxa24uu"
coprocessor_app_id = "ac2835ba2ef5bdaf10014baca3823fa6102b4b9026ea93ed44aa3d9314240eac"
